[package]
name = "hq"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1", features = ["derive"] }
requestty = "0.3.0"
chrono = "0.4"
dirs = "4.0"